OBJECT_ATTRIBUTES = [
    "ObjectName",
    "parentReceptacles",
    "receptacleObjectIds",
    "distance",
    "mass",
    "size",
    "ObjectTemperature",
    "breakable",
    "cookable",
    "dirtyable",
    "isBroken",
    "isCooked",
    "isDirty",
    "isFilledWithLiquid",
    "isOpen",
    "isPickedUp",
    "isSliced",
    "isToggled",
    "moveable",
    "openable",
    "pickupable",
    "receptacle",
    "salientMaterials_Ceramic",
    "salientMaterials_Fabric",
    "salientMaterials_Food",
    "salientMaterials_Glass",
    "salientMaterials_Leather",
    "salientMaterials_Metal",
    "salientMaterials_Paper",
    "salientMaterials_Plastic",
    "salientMaterials_Rubber",
    "salientMaterials_Soap",
    "salientMaterials_Sponge",
    "salientMaterials_Stone",
    "salientMaterials_Wax",
    "salientMaterials_Wood",
    "sliceable",
    "toggleable",
]


ACTIONS_MAPPER = {
    0: "DirtyObject",
    1: "OpenObject",
    2: "SliceObject",
    3: "ToggleObjectOff",
    4: "ToggleObjectOn",
    5: "EmptyLiquidFromObject",
    6: "PickupObject",
    7: "HeatUpPan",
    8: "CloseObject",
    9: "PutObject",
}
