# needed to validate the config yaml
defaults:
  - base_config 
  - _self_

run_name: "images_fuse"
gpus: "1"
seed: 42
fast: false
images: true
num_workers: 6

hydra:
  output_subdir: null
  run:
    dir: .

paths:
  # path to directory containing input data
  input_dir: "${hydra:runtime.cwd}/data"
  # path to directory to save output data
  output_dir: "${hydra:runtime.cwd}/output"

model:
  hidden_size: 64
  num_layers: 1
  num_heads: 4
  bert_model: "roberta-base"
  dropout: 0.1
  fuse_images: true
  
pretrain:
  batch_size: 1024
  max_epochs: 80
  learning_rate: 0.001

nlu:
  batch_size: 128
  max_epochs: 80
  learning_rate: 0.00001



